services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=sid
      - POSTGRES_USER=sid
      - POSTGRES_DB=shelter

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    
  etl:
    build: .
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - db    
    environment:
      - DB_HOST=db
    



volumes:
  db_data: